language: rust
cache: cargo
dist: bionic

os:
  - linux
  #- osx
  #- windows

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUSTFLAGS="-C link-dead-code"

script:
    - cargo build --verbose

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - stage: static analysis
      name: "Clippy"
      addons: { }
      rust: stable
      cache:
        cargo: true
      before_script: rustup component add clippy
      script: cargo clippy -- -D clippy::all
      after_success:

stages:
    #- pre-build checks
    - build and test
    - static analysis