[package]
name = "lsys"
version = "0.1.0"
authors = ["Robin Chavignat <r.chavignat@gmail.com>"]
edition = "2018"
repository = "https://github.com/Robzz/lsys"

[dependencies]
image = "0.23"
imageproc = "0.20"
nalgebra = "0.21"
thiserror = "1.0"